/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const handlerAICore = require('./code/ai-core-handler.js');

class GenAIService extends LCAPApplicationService {
    async init() {

        this.on('connectToGenAI', async (req) => {
            const prompt = '%' + req.data.prompt + '%';
            const chatModelName = req.data.chatModelName;
            const withRAG = req.data.withRAG;

            return handlerAICore.connectToGenAIHub(prompt, chatModelName, withRAG);
        });

        return super.init();
    }
}


module.exports = {
    GenAIService
};